# Generated by Django 4.0 on 2023-01-06 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_device_prediction_alter_device_crutch'),
        ('device', '0013_remove_rawdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('timestamp', models.CharField(default='', max_length=30)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.device')),
            ],
        ),
    ]
