# Generated by Django 4.1.5 on 2023-01-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0008_device_prediction_alter_device_crutch"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="profile_picture",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
