# Generated by Django 4.1.5 on 2023-01-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="profile_picture",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
